import { Inter } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Desus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className=" font-Poppins">
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
